import re
import scml
from typing import Iterable, Tuple

__all__ = ["Slang"]

log = scml.get_logger()

DEFAULT_RULES: Tuple[Tuple[str, str], ...] = (
    ("+1", "I agree"),
    ("10-4", "I understand your transmission"),
    ("1337", "elite, highly skilled"),
    ("4oj", "Fourth of July"),
    ("5-0", "police officers or warning that police is approaching"),
    ("8-ball", "1/8 of an ounce (approximately 3.5 grams) of abused drugs"),
    ("af", "as fuck; expression of annoyance, contempt or impatience"),
    ("a-cup", "size of a woman's breast"),
    ("a1", "of excellent grade or condition"),
    ("adv", "advance"),
    ("afaik", "as far as i know"),
    ("afk", "away from keyboard"),
    ("afro", "African or African American, especially of a style of music or clothing"),
    ("afu", "all fucked up; total failure or disaster"),
    ("aggro", "aggressive, provoking or violent behaviour"),
    ("aka", "also known as"),
    ("alot", "a lot"),
    ("alt+f4", "to exit a computer program, video game or chat room"),
    (
        "apb",
        "All Points Bulletin which is a broadcast to all police officers, often with information about a suspect who is to be detained.",
    ),
    ("asap", "as soon as possible"),
    ("aspie", "person who has Asperger's Syndrome"),
    ("assgut", "slur for an overweight person"),
    ("asshat", "slur for a stupid or contemptible person"),
    ("atm", "at the moment"),
    ("aussie", "Australian"),
    ("awol", "Absent Without Official Leave"),
    ("aww", "expression of endearment or affection"),
    ("b&d", "sexual practice of Bondage and Domination"),
    ("b.o.", "body odour"),
    ("badass", "a tough, uncompromising, or intimidating person"),
    ("bagina", "vagina"),
    ("baka", "slur for a stupid or contemptible person"),
    ("baller", "affluent lifestyle"),
    ("ballin", "affluent lifestyle"),
    ("bamf", "a tough, uncompromising, or intimidating person"),
    ("bandz", "whole stack of dollar notes"),
    ("banger", "awesome or attractive person"),
    ("bangin", "awesome or attractive"),
    ("barf", "vomit"),
    ("bb", "baby"),
    ("bbq", "barbecue"),
    ("bbs", "be back soon"),
    ("bbts", "big black titties"),
    ("bbw", "overweight woman"),
    ("bdsm", "sexual practice of Bondage, Domination, Sadism and Masochism"),
    ("beamer", "nice car"),
    ("beaner", "illegal immigrant"),
    ("bender", "homosexual male"),
    ("benzo", "drugs used for treatment of anxiety"),
    ("beotch", "bitch; slur for an annoying or unpleasant female"),
    ("beso", "to kiss"),
    ("besos", "kisses"),
    ("bestie", "best friend"),
    ("bf", "boyfriend or best friend"),
    ("bfd", "big fucking deal"),
    ("bff", "best friends forever"),
    ("bffl", "best friends for life"),
    ("bfl", "scammed"),
    ("bfo", "best friend at work"),
    ("biatch", "bitch; slur for an annoying or unpleasant female"),
    ("bilf", "babysitter I will like to fuck"),
    ("bilk", "bitch I will like to kill"),
    ("bint", "bitch; slur for an annoying or unpleasant female"),
    ("biotch", "bitch; slur for an annoying or unpleasant female"),
    ("bj", "blow job; sexual act"),
    ("bleh", "expression of indifference or boredom"),
    ("bling", "expensive jewellery"),
    ("bmao", "blow my ass off"),
    (
        "bobfoc",
        "Body Off Baywatch, Face Off Crimewatch. A person who possesses a killer body but has a face that only a mother could love.",
    ),
    ("boi", "boyish"),
    ("boink", "sexual intercourse"),
    ("bolo", "police term for Be On the Lookout"),
    ("boned", "to be caught in a very bad situation"),
    ("boner", "to be sexually aroused"),
    ("boning", "sexual intercourse"),
    ("bonk", "sexual intercourse"),
    ("boob", "a woman's breast"),
    ("boobs", "a woman's breast"),
    ("booger", "a piece of dried nasal mucus"),
    ("boong", "Australian"),
    ("booya", "exclamation of excitement"),
    ("booyah", "exclamation of excitement"),
    ("borgle", "stupid behaviour"),
    ("borked", "to cause equipment to stop working"),
    ("boytoy", "attractive male friend"),
    ("brb", "be right back"),
    ("bro", "male friend"),
    ("brodeo", "A get-together or a party where the attendance is prodominantly male."),
    ("brofie", "a photograph that one has taken of oneself together with male friends"),
    ("broham", "male friend"),
    ("brojob", "homosexual male"),
    ("brolic", "muscular well-built male"),
    ("broly", "male friend"),
    ("bruh", "male friend"),
    ("bruv", "male friend"),
    ("bsod", "Blue Screen Of Death, a serious technical glitch"),
    ("btfo", "a sports term where the underdog team wins by a large margin"),
    ("btjm", "but that is just me"),
    ("btw", "by the way"),
    ("bub", "friend"),
    ("bubs", "friends"),
    ("bugger", "slur for an annoying or unpleasant person"),
    ("bukake", "sexual act that is derogatory for women"),
    ("bummer", "a disappointing or unpleasant situation or experience"),
    (
        "burner",
        "A throwaway prepaid cellphone, typically used by dealers. Used until the minutes are up, then thrown away so they cannot be tapped.",
    ),
    ("bwc", "man's penis"),
    ("byob", "bring your own beer"),
    ("c-cup", "size of a woman's breast"),
    ("caking", "flirting"),
    ("catty", "subtly or indirectly insulting"),
    ("cexy", "sexy"),
    ("chigga", "Asians who are influenced by urban hip-hop culture"),
    ("chink", "racist term for Chinese people"),
    ("chinks", "racist term for Chinese people"),
    ("chinky", "racist term for Chinese people"),
    ("chirps", "chat up, woo, or court another person"),
    ("chulo", "good looking or sexually attractive"),
    ("chump", "slur for a stupid or contemptible person"),
    ("ciao", "greeting hello or goodbye"),
    ("cim", "Cum in Mouth"),
    ("cocos", "Cocaine"),
    ("coed", "integrated education of men and women at the same school facilities"),
    ("colby", "gangster"),
    ("commie", "derogatory term for a communist"),
    ("convo", "conversation"),
    ("cooch", "profanity for female genitals"),
    ("coolie", "indentured labourers"),
    ("coom", "orgasm"),
    ("cooter", "profanity for female genitals"),
    ("copped", "receive or attain something beneficial"),
    ("cougar", "an older woman who looks to get into a relationship with younger men"),
    ("couger", "an older woman who looks to get into a relationship with younger men"),
    ("cretin", "slur for a stupid or contemptible person"),
    ("crikey", "An Australian exclamation of surprise or bewilderment"),
    ("crusty", "rude or harsh person"),
    ("csb", "expression of disbelief"),
    (
        "csi",
        "search for and publish private or identifying information about (a particular individual) on the internet, typically with malicious intent",
    ),
    ("ctfd", "Calm the fuck down"),
    ("ctfu", "laughing; crack the fuck up"),
    ("cthu", "laughing; crack the hell up"),
    ("cuck", "to make a cuckold of one's spouse"),
    ("cuddy", "friend"),
    ("cuffed", "in a heterosexual relationship with someone"),
    ("cunny", "profanity for female genitals"),
    ("cunt", "profanity for female genitals"),
    ("cunty", "bitch; slur for an annoying or unpleasant female"),
    ("cuz", "because"),
    ("cya", "bid goodbye"),
    (
        "d'oh",
        "expression of annoyance with a foolish or stupid action, especially one's own",
    ),
    ("d-boy", "drug dealer"),
    ("d-cup", "size of a woman's breast"),
    ("d.o.a", "dead on arrival"),
    ("dae", "Does Anybody Else"),
    ("dafuq", "expression of confusion, what the fuck"),
    ("daggy", "out of fashion or untidy"),
    ("dago", "racist slur for Italians"),
    ("damnit", "damn; exclamation of anger or frustration or to add emphasis"),
    ("dang", "damn; exclamation of anger or frustration or to add emphasis"),
    ("dap", "The knocking of fists together as a greeting, or form of respect."),
    ("daps", "The knocking of fists together as a greeting, or form of respect."),
    ("darkie", "racist slur for black people"),
    ("darky", "racist slur for black people"),
    ("dawg", "friend of an African-American ethnic background"),
    ("dayum", "damn; exclamation of anger or frustration or to add emphasis"),
    ("ddf", "drug and disease free"),
    ("deets", "details"),
    ("dego", "racist slur for Italians"),
    ("derpy", "awkward or embarrassing behaviour"),
    ("dfk", "deep french kissing"),
    ("dfl", "in last position or rank"),
    ("dftba", "do not forget to be awesome"),
    ("dfw", "psyched to chill and hang out with friends"),
    ("dgaf", "don't give a fuck"),
    ("dibs", "to claim something"),
    ("diddle", "female masturbation"),
    ("dilf", "dad I will like to fuck"),
    ("dinger", "marksmanship with small arms"),
    ("dink", "Dual Income No Kids"),
    ("diss", "speak disrespectfully to or criticize"),
    ("diu", "fuck; expression of annoyance, contempt or impatience"),
    ("diy", "Do It Yourself"),
    (
        "dnb",
        "a 'Do Nothing Bitch'. A girl who wants to be all pretty and fancy, just to have someone take care of her.",
    ),
    ("doa", "dead on arrival"),
    ("doggy", "sexual intercourse"),
    ("dolt", "slur for a stupid or contemptible person"),
    ("doodoo", "faeces"),
    ("dookie", "faeces"),
    ("doosh", "annoying or unpleasant person"),
    ("doozy", "an extraordinary one of its kind"),
    ("dork", "an odd, socially awkward, unstylish person"),
    ("dosh", "monetary amount"),
    ("douche", "annoying or unpleasant person"),
    ("doussy", "annoying or unpleasant person"),
    (
        "dox",
        "search for and publish private or identifying information about (a particular individual) on the internet, typically with malicious intent",
    ),
    ("dps", "gaming term for damage per second"),
    ("dtmfa", "to get out of a toxic relationship"),
    ("dtr", "Define The Relationship"),
    ("duces", "bid goodbye"),
    ("dud", "a thing that fails to work properly or is otherwise unsatisfactory"),
    ("dude", "friend"),
    ("duece", "shit; an exclamation of disgust, anger, or annoyance"),
    ("dueces", "shit; an exclamation of disgust, anger, or annoyance"),
    ("duh", "comment on a foolish or stupid action, especially someone else's"),
    ("dui", "Driving Under the Influence (of alchohol)"),
    ("dunch", "not quite dinner but definitely past lunch"),
    ("dunno", "do not know"),
    ("dunny", "friend"),
    ("dweeb", "a boring, studious, or socially inept person"),
    ("dweet", "tweeting while intoxicated"),
    ("dyme", "very attractive female"),
    (
        "e-bile",
        "an email sent for the purpose of spewing anger, vitriol and complaint.",
    ),
    ("e-cup", "size of a woman's breast"),
    ("e-peen", "ego or pride in the virtual world"),
    ("e-void", "Avoiding all digital communciations from someone"),
    ("ebaum", "to steal something and claim it as your own"),
    (
        "ecchi",
        "a subgenre of Japanese manga, anime, computer games, etc., characterized by light, playful sexual themes and imagery.",
    ),
    ("efg", "Epic Fail Guy"),
    ("emo", "emotional"),
    ("esrun", "To send out automated spam"),
    ("ew", "exclamation of disgust"),
    ("eww", "exclamation of disgust"),
    ("f'it", "fuck it; expression of annoyance, contempt or impatience"),
    ("f**k", "fuck; expression of annoyance, contempt or impatience"),
    ("f.a.m.", "family above money"),
    ("f.t.w.", "for the win"),
    ("f/u", "follow up"),
    ("fab", "fabulous"),
    ("fag", "faggot; slur for an annoying or unpleasant person"),
    ("fagget", "faggot; slur for an annoying or unpleasant person"),
    ("faggit", "faggot; slur for an annoying or unpleasant person"),
    ("faggle", "a group of homosexual males"),
    ("fagit", "faggot; slur for an annoying or unpleasant person"),
    ("fags", "faggot; slur for an annoying or unpleasant person"),
    ("fai", "forget about it"),
    ("fam", "family"),
    ("fap", "masturbation"),
    ("fape", "masturbation"),
    ("fappy", "masturbation"),
    ("faps", "masturbation"),
    ("fark", "fuck; expression of annoyance, contempt or impatience"),
    ("fatass", "slur for an overweight person"),
    ("fb", "facebook"),
    (
        "fbgm",
        "fuck bitches get money; profanity for saying one's male friends are more important than female friends",
    ),
    ("fbsm", "Full Body Sensual Massage"),
    ("fcuk", "fuck; expression of annoyance, contempt or impatience"),
    ("feces", "faeces"),
    ("feck", "fuck; expression of annoyance, contempt or impatience"),
    ("feen", "craving"),
    ("feenin", "craving"),
    ("felch", "derogatory sexual act"),
    ("fellas", "firends"),
    ("feltch", "derogatory sexual act"),
    ("femdom", "female domination, a sexual act"),
    ("ffl", "laughing; falling from laughing"),
    ("ffox", "firefox browser"),
    ("ffs", "for fuck's sake; expression of annoyance, contempt or impatience"),
    ("fgt", "faggot; slur for an annoying or unpleasant person"),
    ("fify", "fixed it for you"),
    ("fiiq", "fuck it I quit; expression of annoyance, contempt or impatience"),
    ("fittie", "sexually attractive"),
    ("five-o", "police officers"),
    ("flakey", "unreliable, absent-minded or irresponsible"),
    ("flamer", "flamboyant homosexual"),
    ("fleek", "extremely good, attractive, or stylish"),
    ("flendy", "trendy"),
    ("flexin", "showing off"),
    ("floozy", "slut; slur for a sexually promiscuous female"),
    ("flope", "uncool or unpopular person"),
    ("fluck", "flying fuck; expression of annoyance, contempt or impatience"),
    ("flurge", "slur for a sexually unattractive female"),
    ("fmi", "for my information"),
    ("fml", "fuck my life; expression of annoyance, contempt or impatience"),
    ("fng", "new joiner who is inexperienced or unskilled"),
    ("foad", "fuck off and die; expression of annoyance, contempt or impatience"),
    ("fof", "frown on face"),
    ("fogo", "fear of going out"),
    ("foh", "fuck off from here; expression of annoyance, contempt or impatience"),
    ("fomo", "fear of missing out"),
    ("foodie", "a person who looks for and enjoys good food"),
    ("footy", "football or soccer sports"),
    ("fosu", "fear of sobering up"),
    ("frack", "fuck; expression of annoyance, contempt or impatience"),
    ("frag", "kill an enemy in a video game"),
    ("frak", "fuck; expression of annoyance, contempt or impatience"),
    ("frape", "to prank someone's social media profile"),
    ("fraped", "to prank someone's social media profile"),
    ("frig", "female masturbation"),
    ("ftfy", "fixed that for you"),
    ("ftl", "for the loss"),
    ("ftmfw", "for the win"),
    ("fts", "fuck that shit; expression of annoyance, contempt or impatience"),
    ("ftw", "for the win"),
    ("fu", "fuck you; expression of annoyance, contempt or impatience"),
    ("fuark", "fuck; expression of annoyance, contempt or impatience"),
    (
        "fubar",
        "fucked up beyond all recognition; expression of annoyance, contempt or impatience",
    ),
    ("fud", "scare tactics that employ Fear, Uncertainty and Doubt"),
    ("fufu", "fake"),
    ("fug", "fucking ugly"),
    ("fugazi", "fake"),
    ("fugazy", "fake"),
    ("fugly", "fucking ugly"),
    ("fuk", "fuck; expression of annoyance, contempt or impatience"),
    ("fukkem", "fuck them; expression of annoyance, contempt or impatience"),
    ("fundie", "fundamentalist or strict advocate"),
    ("fungry", "fucking hungry; very hungry"),
    ("fuq", "fuck; expression of annoyance, contempt or impatience"),
    ("futa", "fucked up the ass; expression of annoyance, contempt or impatience"),
    ("fwiw", "for what it's worth"),
    ("fyi", "for your information"),
    (
        "g-spot",
        "a sensitive area believed to exist in the anterior wall of the vagina and to be highly erogenous",
    ),
    ("g2g", "got to go"),
    ("gah", "exclamation of anger or frustration"),
    ("gaijin", "foreigner"),
    ("gams", "attractive pair of female legs"),
    ("ganga", "slut; slur for a sexually promiscuous female"),
    ("gank", "to steal something or kill someone "),
    ("ganked", "to steal something or kill someone "),
    ("gawd", "exclamation of surprise or shock"),
    ("gbf", "gay best friend"),
    ("gdb", "bitch; slur for an annoying or unpleasant female"),
    (
        "gdi",
        "God Damn Independent, a college student who is not in a fraternity or sorority.",
    ),
    ("geezer", "slur for older male"),
    ("getcha", "I understand"),
    ("gf", "girlfriend"),
    ("gfe", "Girl Friend Experience."),
    ("gfy", "good for you"),
    ("gg", "good game"),
    ("ghey", "gay"),
    ("giggin", "dancing well"),
    ("gilf", "Grandmother I would Like to Fuck"),
    ("gimp", "slur for a stupid or contemptible person"),
    ("gink", "racist slur for a person of Indian descent"),
    ("gitgo", "from the very beginning"),
    ("gj", "good job"),
    ("gl", "good luck"),
    ("glhf", "good luck have fun"),
    ("gmas", "give me a second"),
    ("gmy", "good man yourself, to appreciate someone's action"),
    ("gnar", "difficult, dangerous, or challenging"),
    ("gnarly", "difficult, dangerous, or challenging"),
    ("goga", "girl-on-girl action"),
    ("gooday", "greeting hello"),
    ("gook", "racist slur for Korean people"),
    ("goosed", "to pinch someone's buttocks"),
    ("gorpy", "sloppy or messy"),
    ("gosu", "a person who is highly skilled especially in video games"),
    ("gotcha", "I understand"),
    ("gpoy", "gratuitous picture of yourself"),
    ("greebo", "an unkempt or dirty-looking young man"),
    ("greezy", "pleasing or good form or a happy occurrence"),
    ("gress", "racist slur for black female"),
    ("gringo", "foreigner"),
    ("groovy", "fashionable and exciting"),
    ("gtfo", "get the fuck out; expression of annoyance, contempt or impatience"),
    ("gtg", "got to go"),
    ("guero", "fair skinned or light haired person"),
    ("guey", "friend"),
    ("gump", "slur for a stupid or contemptible person"),
    ("gurl", "girl"),
    ("gz", "congratulations"),
    ("h-o-e", "whore; slur for a sexually promiscuous female"),
    ("h.m.u", "hit me up"),
    ("h4x0r", "computer hacker"),
    ("habeeb", "expression of endearment or affection"),
    ("habibi", "expression of endearment or affection"),
    ("habs", "expression of endearment or affection"),
    ("hai", "greeting hello"),
    ("hangry", "very hungry"),
    ("haole", "racist slur for white people"),
    ("hapa", "of mixed racial heritage with Pacific Islander ancestry"),
    ("hardon", "sexually aroused; hard-on"),
    ("hawt", "sexually attractive; hot"),
    ("hazing", "bullying new joiners through some initiation rite"),
    ("hbd", "happy birthday"),
    ("hbic", "bitch; slur for an annoying or unpleasant female"),
    ("heffa", "slur for an overweight person"),
    ("heffer", "slur for an overweight person"),
    ("hiney", "buttocks"),
    ("hinky", "unreliable or faulty"),
    ("hj", "hand job; sexual act"),
    ("hobo", "a homeless person; a tramp or vagrant"),
    ("hoebag", "whore; slur for a sexually promiscuous female"),
    ("hoes", "whore; slur for a sexually promiscuous female"),
    ("hola", "greeting hello"),
    ("holla", "greeting hello"),
    ("homey", "friend"),
    ("homie", "friend"),
    ("homies", "friends"),
    ("homo", "slur for homosexuals"),
    ("honkey", "slur for people from Hong Kong"),
    ("honkie", "slur for people from Hong Kong"),
    ("honky", "slur for people from Hong Kong"),
    ("hooah", "Heard Understood Acknowledged"),
    ("hooch", "alchohol"),
    ("hoodie", "sweatshirt with a hood"),
    ("hooker", "female prostitute"),
    ("hoorah", "Heard Understood Acknowledged"),
    ("hoprah", "fan of Oprah Winfrey"),
    ("hore", "whore; slur for a sexually promiscuous female"),
    ("horney", "sexually aroused"),
    ("horny", "sexually aroused"),
    ("hoser", "slur for a stupid or contemptible person"),
    ("hott", "sexually attractive"),
    ("hottie", "sexually attractive"),
    ("howdy", "greeting hello"),
    ("hpoa", "sexually attractive; hot piece of ass"),
    (
        "hprl",
        "Happy Pony Rainbow Land; a place or message board where no one ever disagrees with anyone else",
    ),
    ("htf", "how the fuck; expression of annoyance, contempt or impatience"),
    ("hth", "hope that helps"),
    ("hubby", "husband"),
    (
        "hugbox",
        "environment which validates a limited set of ideas and feelings; an echo chamber",
    ),
    ("huggle", "hug"),
    ("humps", "The upper and lower curves of a woman's body"),
    ("hungs", "hungry"),
    ("huns", "slur for an annoying or unpleasant person"),
    ("hunty", "bitch; slur for an annoying or unpleasant female"),
    ("hussie", "whore; slur for a sexually promiscuous female"),
    ("hussy", "whore; slur for a sexually promiscuous female"),
    ("huta", "slur for a stupid or contemptible person"),
    ("hutch", "bitch; slur for an annoying or unpleasant female"),
    ("huzzah", "hooray"),
    ("hwp", "Height Weight Proportional"),
    ("hxc", "hardcore"),
    ("hyper", "hyperactive or unusually energetic"),
    ("i124q", "I want to fuck you"),
    ("iawtc", "I agree"),
    ("ibtl", "in before the forum thread is locked"),
    ("idd", "indeed"),
    (
        "idfka",
        "I don't fucking know anymore; expression of annoyance, contempt or impatience",
    ),
    ("idfwu", "I don't fuck with you; expression of annoyance, contempt or impatience"),
    ("idgaf", "expression of indifference; I don't give a fuck"),
    ("idgi", "I do not understand"),
    ("idk", "I do not know"),
    ("iffy", "Unreliable, uncertain or suspicious"),
    (
        "iflml",
        "I fucking love my life; expression of annoyance, contempt or impatience",
    ),
    ("iirc", "If I Recall Correctly"),
    ("ijs", "I'm just saying, to add emphasis or express irony"),
    ("ikr", "I know right"),
    ("ily", "I love you"),
    ("ilysm", "I love you"),
    ("ima", "I am going to"),
    ("imao", "In My Arrogant Opinion"),
    ("imba", "imbalanced or unfair advantage, especially in video games"),
    ("imho", "In my humble opinion"),
    ("imma", "I am going to"),
    ("imu", "I miss you"),
    ("imy", "I miss you"),
    ("inb4", "in before another person posts an obvious reply"),
    ("incel", "Involuntary Celibate"),
    ("indie", "small independent group"),
    ("indo", "Indonesian"),
    ("innit", "isn't it"),
    ("intj", "introverted and analytical personality"),
    ("intp", "introverted and analytical personality"),
    ("ioi", "indicator of interest"),
    ("iq", "intelligence quotient"),
    ("irc", "Internet Relay Chat"),
    ("irie", "nice, good, or pleasing, used as a general term of approval"),
    ("irl", "in real life"),
    ("isheep", "fan of Apple brand"),
    ("ityf", "I think you will find"),
    ("iykwim", "If you know what I mean"),
    ("j00", "you"),
    ("jacked", "violent robbery or to express readiness and prepared to do something"),
    ("jaebum", "Korean-American male who is sexually attractive"),
    ("jag", "slur for an annoying or unpleasant person"),
    ("jagoff", "slur for an annoying or unpleasant person"),
    ("jamboy", "slur for indentured servant"),
    ("jamoke", "slur for a stupid or contemptible person"),
    ("jank", "of inferior quality"),
    ("janky", "of inferior quality"),
    ("jap", "slur for Japanese people"),
    ("jewbag", "slur for selfish and greedy person"),
    ("jewed", "slur to be cheated out of something"),
    ("jfc", "Jesus Fucking Christ; expression of annoyance, contempt or impatience"),
    ("jfgi", "Just Fucking Google it; expression of annoyance, contempt or impatience"),
    (
        "jiggy",
        "nervous; active; excitedly energetic. wonderful and exciting, especially because stylish",
    ),
    ("jive", "lively dance"),
    ("jiz", "semen"),
    ("jizz", "semen"),
    ("jk", "just kidding"),
    ("jockin", "The act of obsessing over another with intense affection"),
    (
        "jocks",
        "a person, esp. a young man, who is extremely enthusiastic about and good at sports",
    ),
    ("jugg", "slur for a woman's breasts, especially when large and shapely"),
    ("juggs", "slur for a woman's breasts, especially when large and shapely"),
    ("jugs", "slur for a woman's breasts, especially when large and shapely"),
    ("junkie", "drug addict"),
    ("kaffer", "racist slur for black people"),
    ("kaffir", "racist slur for black people"),
    ("kawaii", "cute and lovely"),
    ("kcco", "keep calm and carry on"),
    ("kek", "laughing"),
    ("keke", "laughing"),
    ("kekeke", "laughing"),
    ("kike", "ethnic slur for Jewish people"),
    ("kikes", "ethnic slur for Jewish people"),
    ("kitteh", "cat"),
    ("kmsl", "laughing; killing myself laughing"),
    ("koon", "racist slur for black people"),
    ("kosher", "genuine and legitimate"),
    (
        "kpg",
        "Keep the Party Going. To maintain a consistent level of fun while undergoing outside strife and turmoil.",
    ),
    ("kraut", "ethnic slur for German people"),
    ("krite", "shit; an exclamation of disgust, anger, or annoyance"),
    ("kthxbi", "okay thank you goodbye"),
    ("kudos", "to earn respect and recognition"),
    ("kuk", "penis"),
    ("kurac", "penis"),
    ("kurva", "whore; slur for a sexually promiscuous female"),
    ("kurwa", "whore; slur for a sexually promiscuous female"),
    ("kush", "abused drugs"),
    ("kuya", "a polite title or form of address for an older man"),
    ("kyke", "ethnic slur for Jewish people"),
    ("l.u.g", "Lesbian until graduation"),
    ("l.u.g.", "Lesbian until graduation"),
    ("l2p", "learn to play"),
    ("l337", "elite or highly skilled"),
    ("l33t", "elite or highly skilled"),
    ("laduzi", "diarrhoea"),
    ("lal", "laughing out loud"),
    ("lampin", "to just chill back and relax while being totally unproductive"),
    ("larp", "live action role play"),
    ("lawl", "laughing out loud"),
    ("lawlz", "laughing out loud"),
    ("lb's", "pounds; weight measurement"),
    ("lbd", "little black dress"),
    ("lbh", "Let's be honest"),
    ("lcts", "Let's change the subject"),
    ("ldoc", "Last day of class"),
    ("ldr", "Long Distance Relationship"),
    ("leeroy", "a dangerously reckless person, especially in video games"),
    ("leet", "elite or highly skilled"),
    ("legit", "genuine and legitimate"),
    ("leng", "to describe someone as good looking"),
    ("lesbo", "homosexual female"),
    ("lesbro", "a male with many homosexual female friends"),
    ("lfg", "Looking for group"),
    ("lgbt", "lesbian, gay, bisexual, transgender and queer or questioning community"),
    ("lgbtq", "lesbian, gay, bisexual, transgender and queer or questioning community"),
    ("lhh", "Laughing hella hard"),
    ("linner", "The meal between lunch and dinner"),
    ("lipper", "racist slur for black people"),
    ("llap", "Live Long And Prosper"),
    ("llello", "abused drugs"),
    ("lls", "laughing like shit"),
    ("lmao", "laughing my ass off"),
    ("lmbo", "laughing my butt off"),
    ("lmfao", "Laughing my fucking ass off"),
    ("lmk", "Let me know"),
    ("lml", "laughing mad loud"),
    ("loco", "crazy in Spanish"),
    ("lol", "laughing out loud"),
    ("lol'd", "laughing out loud"),
    ("loli", "depicting underage females in sexual poses"),
    ("lolol", "laughing out loud"),
    ("lolwut", "laughing out loud"),
    ("lolz", "laughing out loud"),
    ("lomie", "friend"),
    ("lomies", "friend"),
    ("loml", "love of my life"),
    ("lool", "laughing out loud"),
    ("lqtm", "Laughing quietly to myself"),
    ("ltr", "long-term relationship"),
    ("ludder", "slut; slur for a sexually promiscuous female"),
    ("lul", "laughing out loud"),
    ("lulz", "laughing out loud"),
    ("lurker", "someone who follows the forum but doesn't post any messages"),
    ("lurve", "love"),
    ("luv", "love"),
    ("m$", "microsoft is a greedy corporation"),
    ("m'kay", "okay"),
    ("m.i.a.", "Missing in Action"),
    ("m.o.", "a person's way or method of doing something"),
    ("m.v.p", "most valuable player"),
    ("m4m", "homosexual males; men seeking men in an online chat room"),
    ("m8", "greeting hello"),
    ("m8y", "greeting hello"),
    ("macfag", "fans of Apple brand"),
    ("macho", "masculine in an overly assertive or aggressive way"),
    ("maknae", "someone who is the youngest of a group in Korean"),
    ("mamo", "mammogram"),
    ("manbag", "man's testicles"),
    ("mandem", "a group of male friends"),
    ("manko", "profanity for female genitals"),
    ("mantor", "masculine role model or idol"),
    ("maxin", "relaxing"),
    ("mayate", "racist slur for dark skinned person"),
    (
        "mcjob",
        "a menial, low-paying, unskilled job especially in the fast food industry",
    ),
    ("mdma", "abused drugs"),
    (
        "meatox",
        "the act of abstaining from eating meat for a period of time, usually after heavily indulging",
    ),
    ("meh", "expression of indifference or describing something of mediocre quality"),
    (
        "mehkay",
        "expression of indifference or describing something of mediocre quality",
    ),
    (
        "meme",
        "an image, video, piece of text, etc., typically humorous in nature and shared widely",
    ),
    (
        "memes",
        "an image, video, piece of text, etc., typically humorous in nature and shared widely",
    ),
    ("mench", "a role model"),
    ("mensch", "a role model"),
    ("merc", "mercenary"),
    ("merde", "shit; an exclamation of disgust, anger, or annoyance"),
    ("merica", "america"),
    ("merk", "to kill or defeat an opponent"),
    ("merked", "to kill or defeat an opponent"),
    ("merkin", "to kill or defeat an opponent"),
    ("mersh", "abused drugs"),
    ("meth", "abused drugs"),
    ("mfeo", "made for each other"),
    (
        "mfw",
        "my face when; it often appears in a single sentence or in a story, followed by a reaction image that communicates how the poster feels",
    ),
    ("mgmt", "management"),
    (
        "mgtow",
        "an anti-feminist, misogynistic, mostly online community advocating for men to separate themselves from women and from a society which they believe has been corrupted by feminism",
    ),
    ("mierda", "shit; an exclamation of disgust, anger, or annoyance"),
    ("mija", "own children or friends"),
    ("mijo", "close male friend or family member"),
    ("milf", "mother I will like to fuck"),
    ("mimis", "to sleep"),
    ("minga", "damn; exclamation of anger or frustration or to add emphasis"),
    ("minge", "profanity for female genitals"),
    ("minger", "slur for an annoying or unpleasant person"),
    ("minx", "an impudent, cunning, or boldly flirtatious girl or young woman"),
    ("mirf", "Mom I will run from; an unattractive older woman"),
    ("misc", "miscellaneous"),
    ("mistup", "mist up; crying"),
    ("mlia", "My Life is Average"),
    ("mo'", "of an excessive quantity"),
    ("moar", "exclamation wanting more of something"),
    ("mobbin", "group bullying"),
    ("mod", "forum moderator"),
    ("moded", "be the subject of enforcement actions taken by forum moderators "),
    ("mods", "forum moderator"),
    ("mofo", "motherfucker; slur for an annoying or unpleasant person"),
    (
        "mojo",
        "sex appeal or sex drive; it can also mean charm or having some supernatural ability",
    ),
    ("moke", "ethnic slur for Polynesian people"),
    ("momo", "slur for an annoying or unpleasant person"),
    ("moms", "mother"),
    ("mon", "man"),
    ("mong", "slur for a stupid or contemptible person"),
    ("mongo", "slur for people with developmental disorders or mental health issues"),
    ("moob", "the flabby breasts of a man"),
    ("moobs", "the flabby breasts of a man"),
    ("mooch", "ask for or obtain something without paying for it"),
    ("mook", "slur for a stupid or contemptible person"),
    ("moolah", "money"),
    ("mooley", "racist slur for black people"),
    ("moolie", "racist slur for black people"),
    (
        "mosh",
        "dance to rock music in a violent manner involving jumping up and down and deliberately colliding with other dancers",
    ),
    (
        "mosher",
        "dance to rock music in a violent manner involving jumping up and down and deliberately colliding with other dancers",
    ),
    ("motard", "slur for an annoying or unpleasant person"),
    ("mourad", "wanted, desired, wished for, yearned or goal"),
    ("moxie", "force of character, determination, or nerve"),
    ("moxy", "force of character, determination, or nerve"),
    ("mrw", "My Reaction When"),
    ("msog", "multiple shots on goal; to get more of something at a discount"),
    ("mte", "my thoughts exactly"),
    ("muah", "sound of making a kiss"),
    ("muffie", "A Middle-aged Urban Failure"),
    ("muggle", "a person lacking proficiency or skill"),
    ("mula", "money"),
    ("mun", "man"),
    ("mung", "dirty, disgusting or offensive"),
    ("munt", "to vomit or a racist slur for black people"),
    ("munted", "to vomit"),
    ("munter", "slur for an unattractive female"),
    ("muppet", "incompetent or foolish person"),
    ("murica", "america"),
    ("murked", "To be badly defeated at something"),
    ("murkin", "the hair of the female genitalia"),
    ("murse", "a man's purse; a messenger bag or small bag worn with shoulder strap"),
    ("mush", "friend"),
    ("mushky", "mouth"),
    ("muso", "musician"),
    ("mutt", "racist slur for a person of mixed racial descent"),
    ("muzza", "slur for Muslims"),
    ("mvp", "Most Valuable Player"),
    ("myg0t", "to deliberately harass or enrage someone, especially in video games"),
    ("mynx", "an impudent, cunning, or boldly flirtatious girl or young woman"),
    ("n'wah", "slur for foreigner or slave"),
    ("n00b", "noob; an inexperienced or unskilled person, especially in video games"),
    ("n00bs", "noob; an inexperienced or unskilled person, especially in video games"),
    ("naco", "pejorative for a person of low socio-economic status"),
    ("nads", "man's testicles"),
    ("naff", "lacking in style or good taste"),
    ("nakama", "friend"),
    ("nalgas", "buttocks"),
    ("nammer", "ethnic slur for Vietnamese people"),
    ("nang", "excellent or impressive; used as a general term of approval"),
    ("nao", "now"),
    ("narb", "to be sexually aroused for no apparent reason"),
    (
        "narc",
        "narcotics agent; a government official who specializes in laws dealing with illegal drugs",
    ),
    (
        "nark",
        "to secretly inform the authorities about something bad or illegal that someone has done",
    ),
    (
        "narp",
        "non-athletic regular person; used commonly by collegiate athletes in reference to peers not on a sports team",
    ),
    ("natch", "naturally"),
    ("naw", "no"),
    ("nawalt", "not all women are like that"),
    ("nb", "nota bene; used to mark something as particularly important"),
    ("nbd", "no big deal"),
    ("neato", "neat"),
    ("neek", "A cross between a Nerd and a Geek"),
    ("neet", "Not in Education, Employment or Training"),
    (
        "neg",
        "to imply that someone or something is not good enough; to insult with a backhanded compliment or with qualified approval",
    ),
    ("nekkid", "naked"),
    ("neko", "cat"),
    ("neocon", "a person with neoconservative views in politics"),
    ("nerd", "a person who is boringly studious and socially awkward"),
    ("nerds", "a person who is boringly studious and socially awkward"),
    (
        "nerf",
        "To make worse or weaken, usually in the context of weakening something in order to balance out a game",
    ),
    (
        "nerfed",
        "To make worse or weaken, usually in the context of weakening something in order to balance out a game",
    ),
    (
        "newb",
        "new joiner; an inexperienced or unskilled person, especially in video games",
    ),
    (
        "newbie",
        "new joiner; an inexperienced or unskilled person, especially in video games",
    ),
    (
        "newfag",
        "new joiner; an inexperienced or unskilled person, especially in video games",
    ),
    ("nfi", "no fucking idea; I do not know"),
    ("ngl", "not going to lie"),
    ("nib", "New in Box, meaning brand new and never used"),
    ("nig", "racist slur for black people"),
    ("nigga", "racist slur for black people"),
    ("niggah", "racist slur for black people"),
    ("niggar", "racist slur for black people"),
    ("niggas", "racist slur for black people"),
    ("niggaz", "racist slur for black people"),
    ("niglet", "racist slur for black people"),
    ("nignog", "racist slur for black people"),
    ("nigra", "racist slur for black people"),
    ("niknok", "racist slur for black people"),
    (
        "nimby",
        "not in my backyard; a person who objects to the siting of something perceived as unpleasant or hazardous in the area where they live, especially while raising no such objections to similar developments elsewhere",
    ),
    ("nips", "nipples"),
    ("nizzle", "racist slur for black people"),
    ("nizzles", "racist slur for black people"),
    ("nm", "never mind"),
    ("nmu", "not much you; neutral response to a greeting"),
    ("nn", "goodnight"),
    ("noice", "nice or cool"),
    ("nom", "sound made when eating something"),
    ("noob", "noob; an inexperienced or unskilled person, especially in video games"),
    ("noobs", "noob; an inexperienced or unskilled person, especially in video games"),
    ("noogie", "a hard poke or grind with the knuckles, especially on a person's head"),
    ("nookie", "sexual intercourse"),
    ("nope", "no"),
    ("nork", "profanity for a woman's breast"),
    ("nosh", "eat food enthusiastically or greedily"),
    ("nowt", "zero or nothing"),
    ("nrb", "to be sexually aroused for no apparent reason"),
    (
        "nsfl",
        "not safe for life; warning for disturbing content heavy in nudity or profanity",
    ),
    (
        "nsfw",
        "not safe for work; warning for disturbing content heavy in nudity or profanity",
    ),
    ("nub", "noob; an inexperienced or unskilled person, especially in video games"),
    ("nube", "noob; an inexperienced or unskilled person, especially in video games"),
    ("nucca", "racist slur for black people"),
    ("nukka", "racist slur for black people"),
    ("nutjob", "slur for a crazy person"),
    ("nutted", "butt someone with one's head"),
    ("nutter", "slur for a crazy person"),
    ("nvm", "never mind"),
    ("o-face", "orgasm"),
    ("o.p.", "original poster of the forum thread"),
    ("obo", "or best offer"),
    ("odelay", "expression of agreement or enthusiasm for something"),
    ("ofay", "racist slur for white people"),
    ("ofc", "of course"),
    ("ohai", "greeting hello"),
    ("ohn", "oh hell no; exclamation of disapproval"),
    ("oi", "to attract someone's attention, especially in a rough or angry way"),
    ("oic", "oh i see"),
    ("oldfag", "faggot; slur for an annoying or unpleasant person"),
    ("omf", "oh my fucking; exclamation of surprise or shock"),
    ("omfg", "oh my fucking god; exclamation of surprise or shock"),
    ("omfug", "oh my fucking god; exclamation of surprise or shock"),
    ("omg", "oh my god; exclamation of surprise or shock"),
    ("omj", "oh my god; exclamation of surprise or shock"),
    ("omo", "oh my god; exclamation of surprise or shock"),
    ("omw", "on my way"),
    ("on9", "slur for a stupid or contemptible person"),
    ("ontd", "oh no they did not"),
    ("ooc", "out of character"),
    ("oomf", "one of my followers"),
    ("oorah", "exclamation of approval or encouragement"),
    ("ootd", "outfit of the day"),
    ("opa", "older male friend"),
    ("opp", "opposite"),
    ("oppa", "older male friend"),
    ("oppai", "a woman's breasts"),
    ("orale", "exclamation of approval or encouragement"),
    ("orgie", "sex orgy"),
    (
        "otaku",
        "slur for someone who likes to stay home all the time and lacking social skills",
    ),
    ("ott", "over the top"),
    ("otw", "on the way"),
    ("ownage", "the action or fact of utterly defeating an opponent or rival"),
    ("owo", "expression of surprise"),
    ("owt", "anything"),
    ("p.c.", "politically correct"),
    ("paedo", "paedophile"),
    ("paigon", "someone who is a fake, a liar or betrays their friend"),
    ("paki", "ethnic slur for South Asian people from India or Pakistan"),
    ("pakis", "ethnic slur for South Asian people from India or Pakistan"),
    ("papi", "father"),
    ("pawg", "fat ass white girl; ethnic slur for a sexually attractive white female"),
    ("pawned", "the action or fact of utterly defeating an opponent or rival"),
    ("peachy", "feeling fine or satisfied"),
    ("pecker", "a man's penis"),
    ("pedo", "paedophile"),
    ("peen", "a man's penis"),
    ("peepee", "a man's penis or a woman's vagina"),
    ("peeps", "people"),
    ("peewee", "size of a man's penis"),
    ("peon", "someone of the lowest social standing"),
    ("perv", "pervert"),
    ("pfft", "expression of scornful derision"),
    ("pfm", "pray for me"),
    ("pft", "expression of scornful derision"),
    ("phat", "excellent; highly attractive or gratifying"),
    (
        "phobar",
        "photoshopped beyond all recognition; an image that has been heavily modified or retouched such that the person in the image is barely recognisable",
    ),
    ("phuck", "fuck; expression of annoyance, contempt or impatience"),
    ("phwoar", "to express sexual desire"),
    ("pic", "person in charge"),
    ("piff", "nonsense"),
    ("piffle", "nonsense"),
    (
        "pikey",
        "ethnic slur for people who are of the Traveller community, a set of ethno-cultural groups found primarily in Great Britain and Ireland such as the Romanichal Travellers, Welsh Kale, Scottish Lowland Travellers, Scottish Highland Travellers, and Funfair Travellers",
    ),
    ("pilf", "parent I will like to fuck"),
    (
        "pimpin",
        "a man who controls prostitutes and arranges clients for them, taking a percentage of their earnings in return",
    ),
    (
        "pimps",
        "a man who controls prostitutes and arranges clients for them, taking a percentage of their earnings in return",
    ),
    ("pinche", "fuck; expression of annoyance, contempt or impatience"),
    ("ping", "to send a message over a computer network"),
    ("pinga", "man's penis"),
    ("pingas", "man's penis"),
    ("pinay", "Filipino"),
    ("pinoy", "Filipino"),
    ("pissed", "to be drunk or made very annoyed"),
    ("pita", "pain in the ass; a major annoyance"),
    ("pizda", "profanity for female genitals"),
    ("pk", "player kill; player versus player competition in video games"),
    ("pl0x", "please; used to mock new or inexperienced computer users or gamers"),
    (
        "playa",
        "A player is someone who plays the field, or has prowess in gaining romantic and sexual relationships",
    ),
    ("pleb", "pejorative for a person of low socio-economic status"),
    ("plox", "please; used to mock new or inexperienced computer users or gamers"),
    ("plugs", "mention something publicly in order to promote it"),
    ("plur", "The lifestyle concept of Peace, Love, Unity, and Respect"),
    ("pluto", "to downgrade, demote or remove altogether from a select group or list"),
    ("pmsl", "pissing myself laughing"),
    ("pockle", "a clumsy or awkward person"),
    ("polack", "ethnic slur for Polish people"),
    ("polak", "ethnic slur for Polish people"),
    ("poo", "faeces"),
    ("pooch", "dog"),
    ("poon", "profanity for female genitals"),
    ("poop", "faeces"),
    ("pooped", "faeces"),
    ("poopy", "faeces"),
    ("poot", "farting"),
    ("po-po", "police officer"),
    ("popo", "police officer"),
    ("poppet", "expression of endearment or affection"),
    ("poppin", "to get something started"),
    ("porn", "pornography"),
    ("porno", "pornography"),
    ("pos", "piece of shit; slur for an annoying or unpleasant person"),
    ("poser", "someone who is pretentious or tries to fit in but with exaggeration"),
    ("posers", "someone who is pretentious or tries to fit in but with exaggeration"),
    ("poseur", "someone who is pretentious or tries to fit in but with exaggeration"),
    ("pov", "point of view"),
    ("powned", "the action or fact of utterly defeating an opponent or rival"),
    ("ppl", "people"),
    ("pr0n", "pornography"),
    ("precop", "carried out or occurring prior to copulation"),
    ("precum", "semen"),
    ("pree", "sample or taste something"),
    ("preggo", "pregnant"),
    ("prenup", "prenuptial"),
    (
        "preppy",
        "of or typical of a pupil or graduate of an expensive prep school, especially with reference to their neat style of dress",
    ),
    ("preps", "to prepare something"),
    ("primo", "of top quality or importance"),
    (
        "prissy",
        "having or showing the annoying attitude of people who care too much about dressing and behaving properly",
    ),
    (
        "proc",
        "a video gaming term that describes whenever a random gaming item activates, or a random gaming event occurs",
    ),
    ("prolly", "probably"),
    ("pron", "pornography"),
    ("protip", "important tip"),
    (
        "pruno",
        "prison wine is an alcoholic beverage variously made from apples, oranges, fruit cocktail, fruit juices, hard candy, sugar, high fructose syrup, and possibly other ingredients, including crumbled bread",
    ),
    ("psh", "expression of scornful derision"),
    ("psych", "mentally prepare someone for a testing task or occasion"),
    ("psycho", "psychopath"),
    (
        "ptfo",
        "play the fucking objective; exhort team mates to work together for a common goal instead of behaving selfishly",
    ),
    ("pthc", "preteen hardcore pornography"),
    (
        "pua",
        "pick up artist; a man skilled at finding, attracting, and seducing females",
    ),
    ("pube", "pubic hair"),
    ("pubes", "pubic hair"),
    ("pud", "man's penis"),
    ("pug", "pick up group: a group of strangers"),
    ("puke", "vomit"),
    ("puki", "profanity for female genitals"),
    ("pula", "man's penis"),
    ("puma", "an older woman who is attractive"),
    ("punchy", "having punch; forceful, spirited"),
    ("pundai", "profanity for female genitals"),
    ("punk'd", "to be the victim of a prank"),
    ("punter", "a person who gambles especially one who bets against a bookmaker"),
    ("purdy", "pretty or cute"),
    ("purty", "pretty or cute"),
    ("puss", "profanity for female genitals"),
    ("pussey", "profanity for female genitals"),
    ("pussky", "profanity for female genitals"),
    ("puta", "bitch; slur for an annoying or unpleasant female"),
    ("putang", "profanity for female genitals"),
    ("putz", "slur for a stupid or contemptible person"),
    ("pv", "promotional video"),
    ("pwn", "the action or fact of utterly defeating an opponent or rival"),
    ("pwn3d", "the action or fact of utterly defeating an opponent or rival"),
    ("pwnage", "the action or fact of utterly defeating an opponent or rival"),
    ("pwnd", "the action or fact of utterly defeating an opponent or rival"),
    ("pwned", "the action or fact of utterly defeating an opponent or rival"),
    ("pwns", "the action or fact of utterly defeating an opponent or rival"),
    ("pwnt", "the action or fact of utterly defeating an opponent or rival"),
    ("pwp", "incoherent or absent plot"),
    ("pyro", "pyromania"),
    ("pyt", "pretty young thing"),
    ("qft", "quoted for truth; expression of agreement"),
    (
        "qq",
        "crying; used as a taunt in video games against players who seem weak or unskilled",
    ),
    ("qt", "cute"),
    ("queaf", "release of air from the vagina during sexual intercourse"),
    ("queef", "release of air from the vagina during sexual intercourse"),
    ("queff", "release of air from the vagina during sexual intercourse"),
    ("queif", "release of air from the vagina during sexual intercourse"),
    ("quicky", "sexual intercourse"),
    ("quief", "release of air from the vagina during sexual intercourse"),
    ("quif", "release of air from the vagina during sexual intercourse"),
    ("quife", "release of air from the vagina during sexual intercourse"),
    ("quiff", "release of air from the vagina during sexual intercourse"),
    ("quim", "profanity for female genitals"),
    ("qweef", "release of air from the vagina during sexual intercourse"),
    (
        "qwop",
        "a computer game where the player controls an athlete using the Q, W, O, and P keys",
    ),
)


class Slang:
    def __init__(
        self,
        rules: Iterable[Tuple[str, str]] = None,
        prefix: str = "[",
        suffix: str = "]",
    ):
        rs = rules if rules is not None else DEFAULT_RULES
        self._rules = []
        for pattern, replacement in rs:
            pattern = r"[\b\s]" + re.escape(pattern) + r"[\b\s]"
            replacement = f" {prefix}{replacement}{suffix} "
            self._rules.append((re.compile(pattern, re.IGNORECASE), replacement))

    def expand(self, s: str) -> str:
        res = s
        for pattern, replacement in self._rules:
            res = pattern.sub(replacement, res)
        return res
