from scml.nlp import expand_contractions


class TestExpandContractions:
    def test_case_1(self):
        assert expand_contractions("Ain't") == "are not"
        assert expand_contractions("ain't") == "are not"
        assert expand_contractions("aren't") == "are not"
        assert expand_contractions("can't") == "cannot"
        assert expand_contractions("can't've") == "cannot have"
        assert expand_contractions("'cause") == "because"
        assert expand_contractions("could've") == "could have"
        assert expand_contractions("couldn't") == "could not"
        assert expand_contractions("couldn't've") == "could not have"
        assert expand_contractions("didn't") == "did not"
        assert expand_contractions("doesn't") == "does not"
        assert expand_contractions("don't") == "do not"
        assert expand_contractions("hadn't") == "had not"
        assert expand_contractions("hadn't've") == "had not have"
        assert expand_contractions("hasn't") == "has not"
        assert expand_contractions("haven't") == "have not"
        assert expand_contractions("he'd") == "he would"
        assert expand_contractions("he'd've") == "he would have"
        assert expand_contractions("he'll") == "he will"
        assert expand_contractions("he'll've") == "he will have"
        assert expand_contractions("he's") == "he is"
        assert expand_contractions("how'd") == "how did"
        assert expand_contractions("how'd'y") == "how do you"
        assert expand_contractions("how'll") == "how will"
        assert expand_contractions("how's") == "how is"
        assert expand_contractions("I'd") == "I would"
        assert expand_contractions("I'd've") == "I would have"
        assert expand_contractions("I'll") == "I will"
        assert expand_contractions("I'll've") == "I will have"
        assert expand_contractions("I'm") == "I am"
        assert expand_contractions("I've") == "I have"
        assert expand_contractions("isn't") == "is not"
        assert expand_contractions("it'd") == "it would"
        assert expand_contractions("it'd've") == "it would have"
        assert expand_contractions("it'll") == "it will"
        assert expand_contractions("it'll've") == "it will have"
        assert expand_contractions("it's") == "it is"
        assert expand_contractions("let's") == "let us"
        assert expand_contractions("ma'am") == "madam"
        assert expand_contractions("mayn't") == "may not"
        assert expand_contractions("might've") == "might have"
        assert expand_contractions("mightn't") == "might not"
        assert expand_contractions("mightn't've") == "might not have"
        assert expand_contractions("must've") == "must have"
        assert expand_contractions("mustn't") == "must not"
        assert expand_contractions("mustn't've") == "must not have"
        assert expand_contractions("needn't") == "need not"
        assert expand_contractions("needn't've") == "need not have"
        assert expand_contractions("o'clock") == "of the clock"
        assert expand_contractions("oughtn't") == "ought not"
        assert expand_contractions("oughtn't've") == "ought not have"
        assert expand_contractions("shan't") == "shall not"
        assert expand_contractions("sha'n't") == "shall not"
        assert expand_contractions("shan't've") == "shall not have"
        assert expand_contractions("she'd") == "she would"
        assert expand_contractions("she'd've") == "she would have"
        assert expand_contractions("she'll") == "she will"
        assert expand_contractions("she'll've") == "she will have"
        assert expand_contractions("she's") == "she is"
        assert expand_contractions("should've") == "should have"
        assert expand_contractions("shouldn't") == "should not"
        assert expand_contractions("shouldn't've") == "should not have"
        assert expand_contractions("so've") == "so have"
        assert expand_contractions("so's") == "so is"
        assert expand_contractions("that'd") == "that would"
        assert expand_contractions("that'd've") == "that would have"
        assert expand_contractions("that's") == "that is"
        assert expand_contractions("there'd") == "there would"
        assert expand_contractions("there'd've") == "there would have"
        assert expand_contractions("there's") == "there is"
        assert expand_contractions("they'd") == "they would"
        assert expand_contractions("they'd've") == "they would have"
        assert expand_contractions("they'll") == "they will"
        assert expand_contractions("they'll've") == "they will have"
        assert expand_contractions("they're") == "they are"
        assert expand_contractions("they've") == "they have"
        assert expand_contractions("to've") == "to have"
        assert expand_contractions("wasn't") == "was not"
        assert expand_contractions("we'd") == "we would"
        assert expand_contractions("we'd've") == "we would have"
        assert expand_contractions("we'll") == "we will"
        assert expand_contractions("we'll've") == "we will have"
        assert expand_contractions("we're") == "we are"
        assert expand_contractions("we've") == "we have"
        assert expand_contractions("weren't") == "were not"
        assert expand_contractions("what'll") == "what will"
        assert expand_contractions("what'll've") == "what will have"
        assert expand_contractions("what're") == "what are"
        assert expand_contractions("what's") == "what is"
        assert expand_contractions("what've") == "what have"
        assert expand_contractions("when's") == "when is"
        assert expand_contractions("when've") == "when have"
        assert expand_contractions("where'd") == "where did"
        assert expand_contractions("where's") == "where is"
        assert expand_contractions("where've") == "where have"
        assert expand_contractions("who'll") == "who will"
        assert expand_contractions("who'll've") == "who will have"
        assert expand_contractions("who's") == "who is"
        assert expand_contractions("who've") == "who have"
        assert expand_contractions("why's") == "why is"
        assert expand_contractions("why've") == "why have"
        assert expand_contractions("will've") == "will have"
        assert expand_contractions("won't") == "will not"
        assert expand_contractions("won't've") == "will not have"
        assert expand_contractions("would've") == "would have"
        assert expand_contractions("wouldn't") == "would not"
        assert expand_contractions("wouldn't've") == "would not have"
        assert expand_contractions("y'all") == "you all"
        assert expand_contractions("y'all'd") == "you all would"
        assert expand_contractions("y'all'd've") == "you all would have"
        assert expand_contractions("y'all're") == "you all are"
        assert expand_contractions("y'all've") == "you all have"
        assert expand_contractions("you'd") == "you would"
        assert expand_contractions("you'd've") == "you would have"
        assert expand_contractions("you'll") == "you will"
        assert expand_contractions("you'll've") == "you will have"
        assert expand_contractions("you're") == "you are"
        assert expand_contractions("you've") == "you have"
        assert expand_contractions("dunno") == "do not know"
        assert expand_contractions("'em") == "them"
        assert expand_contractions("everyone's") == "everyone is"
        assert expand_contractions("everybody's") == "everybody is"
        assert expand_contractions("g'day") == "good day"
        assert expand_contractions("gimme") == "give me"
        assert expand_contractions("giv'n") == "given"
        assert expand_contractions("gonna") == "going to"
        assert expand_contractions("gotta") == "got to"
        assert expand_contractions("had've") == "had have"
        assert expand_contractions("he've") == "he have"
        assert expand_contractions("howdy") == "how do you do"
        assert expand_contractions("innit") == "is it not"
        assert expand_contractions("kinda") == "kind of"
        assert expand_contractions("ne'er") == "never"
        assert expand_contractions("o'er") == "over"
        assert expand_contractions("ol'") == "old"
        assert expand_contractions("someone's") == "someone is"
        assert expand_contractions("somebody's") == "somebody is"
        assert expand_contractions("something's") == "something is"
        assert expand_contractions("that'll") == "that will"
        assert expand_contractions("that're") == "that are"
        assert expand_contractions("that've") == "that have"
        assert expand_contractions("there'll") == "there will"
        assert expand_contractions("there're") == "there are"
        assert expand_contractions("these'll") == "these will"
        assert expand_contractions("these're") == "these are"
        assert expand_contractions("these've") == "these have"
        assert expand_contractions("this's") == "this is"
        assert expand_contractions("this'll") == "this will"
        assert expand_contractions("those're") == "those are"
        assert expand_contractions("those'll") == "those will"
        assert expand_contractions("those've") == "those have"
        assert expand_contractions("'tis") == "it is"
        assert expand_contractions("'twas") == "it was"
        assert expand_contractions("wanna") == "want to"
        assert expand_contractions("what'd") == "what did"
        assert expand_contractions("which'd") == "which would"
        assert expand_contractions("which'll") == "which will"
        assert expand_contractions("which're") == "which are"
        assert expand_contractions("which's") == "which is"
        assert expand_contractions("which've") == "which have"
        assert expand_contractions("who'd") == "who did"
        assert expand_contractions("who're") == "who are"
        assert expand_contractions("why'd") == "why did"
        assert expand_contractions("why're") == "why are"
        assert expand_contractions("y'at") == "you at"
